const ROLES = {
  USER: "USER",
  MANAGER: "MANAGER",
  ADMIN: "ADMIN",
};

const ACCESS_TOKEN_EXPIRY = "15m";
const REFRESH_TOKEN_EXPIRY = "7d";

module.exports = { ROLES, ACCESS_TOKEN_EXPIRY, REFRESH_TOKEN_EXPIRY };